protected/models/Order.php
<?php

/**
 * This is the model class for table "tbl_orders".
 *
 * The followings are the available columns in table 'tbl_orders':
 * @property string $id
 * @property string $name
 * @property string $user_id
 * @property string $telephone
 * @property string $date
 * @property integer $cost
 * @property double $coord_x
 * @property double $coord_y
 * @property string $comment
 * @property string $status
 */
class Order extends CActiveRecord
{
    const STATUS_PROCESSING = 'processing';
    const STATUS_DECLINED = 'declined';
    const STATUS_WAITING = 'waiting';
    const STATUS_GRABBED = 'grabbed';
    const STATUS_READY = 'ready';
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_orders';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('telephone', 'required'),
			array('coord_x, coord_y', 'numerical','allowEmpty'=>true),
			array('name', 'length', 'max'=>100),
			array('comment', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, user_id, telephone, date, cost, coord_x, coord_y, comment, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'rel' => array(self::HAS_MANY, 'OrderProduct', 'order_id'),
            'products' => array(self::HAS_MANY, 'Product', 'order_id', 'through'=>'rel'),
            'user'     => array(self::BELONGS_TO, 'UserDataModel', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Номер заказа',
			'name' => 'Название заказа',
			'telephone' => 'Контактный номер телефона',
			'date' => 'Дата заказа',
			'cost' => 'Стоимость',
			'comment' => 'Комментарий',
			'status' => 'Статус заказа',
		);
	}

    public static function getStatuses()
    {
        return array(
            self::STATUS_DECLINED => 'Отменён',
            self::STATUS_GRABBED => 'Отгружен',
            self::STATUS_PROCESSING => 'В обработке',
            self::STATUS_WAITING  => 'Ожидает обработку',
            self::STATUS_READY => 'Готов',
        );
    }

    public static function getStatusClass($status)
    {
        return array(
            self::STATUS_DECLINED => 'danger',
            self::STATUS_GRABBED => 'default',
            self::STATUS_PROCESSING => 'primary',
            self::STATUS_WAITING  => 'info',
            self::STATUS_READY => 'success',
        )[$status];
    }

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical use-case:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search($type = 'user')
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('user_id',$this->user_id,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('cost',$this->cost);
		$criteria->compare('status',$this->status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function beforeSave()
    {
        if (!$this->isNewRecord) {
            return parent::beforeSave();
        }
        if (!Yii::app()->user->isGuest) {
            $this->user_id = Yii::app()->user->id;
        } else {
            $this->name = null;
        }
        $cost = 0;
        foreach ($this->products as $product) {
            $cost += $product->price;
        }
        $this->cost = $cost;
        $this->products = null;
        return parent::beforeSave();
    }

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Order the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/models/Products.php
<?php

/**
 * This is the model class for table "tbl_products".
 *
 * The followings are the available columns in table 'tbl_products':
 * @property string $id
 * @property string $title
 * @property string $width
 * @property string $height
 * @property string $length
 * @property string $category
 * @property string $subcategory
 * @property string $material
 * @property string $description
 * @property string $status
 */
class Products extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_products';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, width, height, length, category, subcategory, material, description, status', 'required'),
			array('title', 'length', 'max'=>50),
			array('width, height, length', 'length', 'max'=>4),
			array('category, subcategory, material', 'length', 'max'=>11),
			array('status', 'length', 'max'=>13),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title, width, height, length, category, subcategory, material, description, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Title',
			'width' => 'Width',
			'height' => 'Height',
			'length' => 'Length',
			'category' => 'Category',
			'subcategory' => 'Subcategory',
			'material' => 'Material',
			'description' => 'Description',
			'status' => 'Status',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('width',$this->width,true);
		$criteria->compare('height',$this->height,true);
		$criteria->compare('length',$this->length,true);
		$criteria->compare('category',$this->category,true);
		$criteria->compare('subcategory',$this->subcategory,true);
		$criteria->compare('material',$this->material,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('status',$this->status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Products the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ProductController.php
<?php

class ProductController extends Controller
{
    public $readableName = array('one'=>'товара', 'many'=>'товаров');
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Product;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Product']))
		{
			$model->attributes=$_POST['Product'];
			if($model->save()) {
                Yii::app()->user->setFlash('success', 'Товар успешно создан!');
                $this->redirect(array('view', 'id' => $model->id));
            }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Product']))
		{
			$model->attributes=$_POST['Product'];
			if($model->save()) {
                Yii::app()->user->setFlash('success', 'Товар успешно обновлён!');
                $this->redirect(array('view', 'id' => $model->id));
            }
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400);
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Product');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Product('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Product']))
			$model->attributes=$_GET['Product'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Product::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404);
		return $model;
	}

}

protected/controllers/ProductsController.php
<?php

class ProductsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Products;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Products']))
		{
			$model->attributes=$_POST['Products'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Products']))
		{
			$model->attributes=$_POST['Products'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Products');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Products('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Products']))
			$model->attributes=$_GET['Products'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Products::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

}

protected/views/product/_form.php
<?php Yii::app()->clientScript->registerCssFile(Yii::app()->assetManager->publish(Yii::getPathOfAlias('webroot.css.fontello').'.css')); ?>
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'product-form',
	'enableAjaxValidation'=>false,
    'htmlOptions'=>array('enctype'=>'multipart/form-data'),
)); ?>

	<p class="help-block">Поля помеченные "<span class="required">*</span>" обязательны для заполнения.</p>

	<?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>50)); ?>

    <?php echo $form->textFieldRow($model,'price',array('class'=>'text-right', 'append'=>'<i class="icon-rub"></i>')); ?>

	<?php echo $form->textFieldRow($model,'width',array('class'=>'text-right','maxlength'=>4, 'append'=>'мм.')); ?>

	<?php echo $form->textFieldRow($model,'height',array('class'=>'text-right','maxlength'=>4, 'append'=>'мм.')); ?>

	<?php echo $form->textFieldRow($model,'length',array('class'=>'text-right','maxlength'=>4, 'append'=>'мм.')); ?>

    <?php echo $form->dropdownListRow($model,'category_id',CHtml::listData(Categories::getAllFree(), 'id', 'name'), array('class'=>'span5'))?>

<?php echo $form->dropdownListRow($model,'material_id',CHtml::listData(Materials::model()->findAll(), 'id', 'name'), array('class'=>'span5'))?>

	<?php echo $form->textAreaRow($model,'description',array('rows'=>6, 'cols'=>50, 'class'=>'span5')); ?>

	<?php echo $form->dropdownListRow($model,'status',$model->statuses,array('class'=>'span5')); ?>

    <?php echo $form->labelEx($model,'images'); ?>
	<?php $this->widget('local.widgets.TbMultiFileUpload', array(
        'model'=>$model,
        'attribute'=>'images',
    )); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Создать' : 'Сохранить',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/product/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5','maxlength'=>11)); ?>

	<?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>50)); ?>

	<?php echo $form->textFieldRow($model,'width',array('class'=>'span5','maxlength'=>4)); ?>

	<?php echo $form->textFieldRow($model,'height',array('class'=>'span5','maxlength'=>4)); ?>

	<?php echo $form->textFieldRow($model,'length',array('class'=>'span5','maxlength'=>4)); ?>

	<?php echo $form->textFieldRow($model,'category_id',array('class'=>'span5','maxlength'=>11)); ?>

	<?php echo $form->textFieldRow($model,'material_id',array('class'=>'span5','maxlength'=>11)); ?>

	<?php echo $form->textAreaRow($model,'description',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

	<?php echo $form->textFieldRow($model,'status',array('class'=>'span5','maxlength'=>13)); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Поиск',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/product/_view.php
<?php
$image = Yii::app()->baseUrl.'/images/none.png';
if(isset($data->images)) {
    $image = Yii::app()->baseUrl.'/images/Product/'.unserialize($data->images)[0];
}
$description = $data->description;
if(strlen($description) > 200) {
    $description = substr($description,0,200).'...';
}
?>
<div class="panel">
    <div class="row-fluid">
        <div class="span4">
            <div class="thumbnail" style="height:200px; margin:0 auto; background-image:url('<?php echo $image;?>');background-repeat:no-repeat;background-size:contain;background-position:center;">
            </div>
        </div>
        <div class="span8 pull-right">
            <div class="span10">
                <h3><?= CHtml::link($data->title,array('view',array('id'=>$data->id))); ?></h3>
                <p class="lead"><?= $description ?></p>
                <p><strong>Высота: </strong><?= $data->width;?>мм.</p>
                <p><strong>Ширина: </strong><?= $data->height;?>мм.</p>
                <p><strong>Глубина: </strong><?= $data->length;?>мм.</p>
            </div>
            <div class="span2">
                <p><?= $data->price; ?>руб.</p>
            </div>
        </div>
    </div>
</div>

protected/views/product/admin.php
<?php
$this->breadcrumbs=array(
	'Товары'=>array('index'),
	'Администрирование',
);

$this->pageTitle = Yii::app()->name.' - Администрирование товаров';

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('product-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Администрирование товаров</h1>

<p>
Вы можете добавить оператор сравнения (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
или <b>=</b>) в начало каждого поля для определения способа сравнения.
</p>

<?php echo CHtml::link('Расширенный поиск','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'product-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
        array(
            'name'=>'title',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по названию',
            ),
        ),
        array(
            'name'=>'width',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по ширине',
            ),
        ),
        array(
            'name'=>'height',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по высоте',
            ),
        ),
        array(
            'name'=>'length',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по глубине',
            ),
        ),
        array(
            'name'=>'material_id',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по материалу'
            ),
            'value'=>'isset($data->material)?$data->material->name:"Нет"',
            'filter'=>CHtml::listData(Materials::model()->findAll(), 'id', 'name'),
        ),
        array(
            'name'=>'category_id',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по категории'
            ),
            'value'=>'isset($data->category)?$data->category->name:"Нет"',
            'filter'=>CHtml::listData(Categories::model()->findAll(), 'id', 'name'),
        ),
        array(
            'name'=>'description',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по описанию',
            ),
        ),
        array(
            'name'=>'status',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по статусу'
            ),
            'value'=>'$data->getStatuses()[$data->status]',
            'filter'=>Product::getStatuses(),
        ),
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'header'=>'Действия',
        ),
	),
)); ?>

protected/views/product/create.php
<?php
$this->breadcrumbs=array(
	'Товары'=>array('index'),
	'Создание',
);

$this->pageTitle = Yii::app()->name.' - Создание товара';

?>

<h1>Создать товар</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/product/index.php
<?php
$this->breadcrumbs=array(
	'Товары',
);

$this->pageTitle = Yii::app()->name.' - Товары';

?>

<h1>Товары</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/product/update.php
<?php
$this->breadcrumbs=array(
	'Товары'=>array('index'),
	$model->title=>array('view','id'=>$model->id),
	'Изменение',
);

$this->pageTitle = Yii::app()->name.' - Изменение товара';

$this->menu=array(
	array('label'=>'Список Товара','url'=>array('index')),
	array('label'=>'Создание Товара','url'=>array('create')),
	array('label'=>'Просмотр Товара','url'=>array('view','id'=>$model->id)),
	array('label'=>'Администрирование Товара','url'=>array('admin')),
);
?>

<h1>Изменение товара "<?php echo $model->title; ?>"</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/product/view.php
<?php

$this->breadcrumbs=array(
	'Товары'=>array('index'),
	$model->title,
);

$this->pageTitle = Yii::app()->name.' - Просмотр товара';

?>

<h1>Просмотр товара "<?php echo $model->title; ?>"</h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'title',
		'width',
		'height',
		'length',
		'category_id',
		'material_id',
		'description',
		'status',
		'images',
	),
)); ?>