protected/models/Order.php
<?php

/**
 * This is the model class for table "tbl_orders".
 *
 * The followings are the available columns in table 'tbl_orders':
 * @property string $id
 * @property string $name
 * @property string $user_id
 * @property string $telephone
 * @property string $date
 * @property integer $cost
 * @property double $coord_x
 * @property double $coord_y
 * @property string $comment
 * @property string $status
 */
class Order extends CActiveRecord
{
    const STATUS_PROCESSING = 'processing';
    const STATUS_DECLINED = 'declined';
    const STATUS_WAITING = 'waiting';
    const STATUS_GRABBED = 'grabbed';
    const STATUS_READY = 'ready';
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_orders';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('telephone', 'required'),
			array('coord_x, coord_y', 'numerical','allowEmpty'=>true),
			array('name', 'length', 'max'=>100),
			array('comment', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, user_id, telephone, date, cost, coord_x, coord_y, comment, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'rel' => array(self::HAS_MANY, 'OrderProduct', 'order_id'),
            'products' => array(self::HAS_MANY, 'Product', 'order_id', 'through'=>'rel'),
            'user'     => array(self::BELONGS_TO, 'UserDataModel', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Номер заказа',
			'name' => 'Название заказа',
			'telephone' => 'Контактный номер телефона',
			'date' => 'Дата заказа',
			'cost' => 'Стоимость',
			'comment' => 'Комментарий',
			'status' => 'Статус заказа',
		);
	}

    public static function getStatuses()
    {
        return array(
            self::STATUS_DECLINED => 'Отменён',
            self::STATUS_GRABBED => 'Отгружен',
            self::STATUS_PROCESSING => 'В обработке',
            self::STATUS_WAITING  => 'Ожидает обработку',
            self::STATUS_READY => 'Готов',
        );
    }

    public static function getStatusClass($status)
    {
        return array(
            self::STATUS_DECLINED => 'danger',
            self::STATUS_GRABBED => 'default',
            self::STATUS_PROCESSING => 'primary',
            self::STATUS_WAITING  => 'info',
            self::STATUS_READY => 'success',
        )[$status];
    }

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical use-case:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search($type = 'user')
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('user_id',$this->user_id,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('cost',$this->cost);
		$criteria->compare('status',$this->status,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function beforeSave()
    {
        if (!$this->isNewRecord) {
            return parent::beforeSave();
        }
        if (!Yii::app()->user->isGuest) {
            $this->user_id = Yii::app()->user->id;
        } else {
            $this->name = null;
        }
        $cost = 0;
        foreach ($this->products as $product) {
            $cost += $product->price;
        }
        $this->cost = $cost;
        $this->products = null;
        return parent::beforeSave();
    }

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Order the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/models/Product.php
<?php

/**
 * This is the model class for table "tbl_product".
 *
 * The followings are the available columns in table 'tbl_product':
 * @property string $id
 * @property string $title
 * @property string $width
 * @property string $height
 * @property string $length
 * @property string $category_id
 * @property string $material_id
 * @property string $description
 * @property string $status
 * @property string $images
 * @property float $price
 */
class Product extends CActiveRecord
{
    const AVAILABLE = 'available';
    const ORDER_ONLY = 'order_only';
    const NOT_AVAILABLE = 'not_available';


    public $widthTo;
    public $lengthTo;
    public $heightTo;
    public $priceTo;

    use ImageMultipleUploadTrait;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_product';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('title, width, height, length, category_id, material_id, description, status', 'required', 'on'=>array('insert','update')),
			array('title', 'length', 'max'=>50),
            array('width, height, length', 'numerical', 'integerOnly'=>true, 'min'=>0, 'max'=>9999),
            array('price', 'numerical'),
            array('category_id', 'exist', 'className'=>'Categories', 'attributeName'=>'id'),
			array('material_id', 'exist', 'className'=>'Materials', 'attributeName'=>'id'),
			array('status', 'in', 'range'=>array_flip($this->getStatuses())),
			array('images, description', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, title, width, height, length, category_id, material_id, description, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'category'  => array(self::BELONGS_TO, 'Categories', 'category_id'),
            'material'  => array(self::BELONGS_TO, 'Materials', 'material_id'),
            'prototype' => array(self::HAS_ONE, 'Product', 'prototype_id'),
            'rel'       => array(self::HAS_MANY, 'OrderProduct','product_id'),
            'orders'    => array(self::MANY_MANY, 'Order', 'product_id','through'=>'rel'),
		);
	}

    public static function getStatuses($addEmpty = false)
    {
        $statuses = array(
            self::AVAILABLE=>'В наличии',
            self::ORDER_ONLY=>'Только на заказ',
            self::NOT_AVAILABLE=>'Нет в наличии',
        );
        if($addEmpty) {
            $statuses[null] = 'Не важно';
        }
        return $statuses;
    }

    public function getUserStatus()
    {
        return self::getStatuses()[$this->status];
    }

    public function isAvailable()
    {
        if(Yii::app()->user->checkAccess('order_only')) {
            return $this->status !== self::NOT_AVAILABLE;
        } else {
            return $this->status === self::AVAILABLE;
        }
    }

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'title' => 'Название',
			'width' => 'Ширина',
			'height' => 'Высота',
			'length' => 'Глубина',
			'category_id' => 'Категория',
			'material_id' => 'Материал',
			'description' => 'Описание',
			'status' => 'Наличие',
			'images' => 'Изображения',
            'price' => 'Цена',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

        if (isset($this->widthTo) || isset($this->width)) {
            $criteria->addBetweenCondition('width', $this->width, $this->widthTo);
        }
        if (isset($this->height) || isset($this->heightTo)) {
            $criteria->addBetweenCondition('height', $this->width, $this->widthTo);
        }
        if (isset($this->length) || isset($this->lengthTo)) {
            $criteria->addBetweenCondition('length', $this->length, $this->lengthTo);
        }
        if (isset($this->price) || isset($this->priceTo)) {
            $criteria->addBetweenCondition('price', $this->price, $this->priceTo);
        }
		$criteria->compare('title',$this->title,true);
		$criteria->compare('category_id',$this->category_id,true);
		$criteria->compare('material_id',$this->material_id,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('status',$this->status,true);
        $criteria->compare('custom',false);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

    public function getStatusAsLabelClass()
    {
        return array(
            self::AVAILABLE => 'success',
            self::ORDER_ONLY => 'info',
            self::NOT_AVAILABLE => 'warning',
        )[$this->status];
    }

    public static function random()
    {
        return self::model()->find('1=1 ORDER BY RAND()');
    }

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Product the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

    public static function getStatusSort()
    {
        return 'CASE '.
            'WHEN status="not_available" THEN 0 '.
            'WHEN status="order_only" THEN 1 '.
            'ELSE 2 '.
            'END ';
    }
}

protected/controllers/ShopController.php
<?php

class ShopController extends Controller
{
    private $menuItem = array();

    public function setMenuItem($menuItem)
    {
        $this->menuItem = $menuItem;
    }

    public function getMenu()
    {
        $menu = array(
            array('label'=>'Магазин', 'url'=>array('shop/index')),
            array('label'=>'Список категорий', 'url'=>array('shop/category')),
            array('label'=>'Поиск', 'url'=>array('shop/products')),
            array('label'=>'Доставка', 'url'=>array('shop/delivery')),
        );
        if(!empty($this->menuItem)) {
            $menu[] = '---';
            $menu[] = $this->menuItem;
        }
        return $menu;
    }

    public function getRightMenu()
    {
        $cartCount = Cart::instance()->count();
        $menu = array();
        if (!$cartCount) {
            $menu[] = array('label'=>'Корзина '.$this->widget('bootstrap.widgets.TbBadge',array(
                    'type'=>'info',
                    'label'=>$cartCount,
                    'htmlOptions'=>array('id'=>'cart-link-badge'),
                ),true),
                'url'=>array('shop/cart'),
            );
        } else {
            $menu[] = array('label'=>'Корзина '.$this->widget('bootstrap.widgets.TbBadge',array(
                    'type'=>'info',
                    'label'=>$cartCount,
                    'htmlOptions'=>array('id'=>'cart-link-badge'),
                ),true), 'items'=>array(
                array('label'=>'Просмотр','url'=>array('shop/cart')),
                array('label'=>'Перейти к оформлению','url'=>array('/orders/create')),
            ));
        }
        if (!Yii::app()->user->isGuest) {
            $menu[] = array('label'=>'Мои заказы', 'url'=>array('/orders'));
        }
        $menu[] = '---';
        return $menu;
    }

    public function filters()
    {
        return array(
            'ajaxOnly + clearCart, addToCart',
            'postOnly + removeFromCart',
        );
    }

    public function actionIndex()
    {
        $categories = Categories::model()->findAll('`parent_id` IS NULL');
        $this->render('index', array(
            'categories'=>$categories,
        ));
    }

    public function actionCategory($id=null)
    {
        $model = null;
        if(isset($id)) {
            $model = Categories::model()->findByPk($id);
            if (!isset($model)) {
                throw new CHttpException(404, 'Категория не найдена!');
            }
            if (empty($model->children)) {
                $this->redirect($this->createUrl('productsByCategory', array('id' => $id)));
            }
        } else {
            $model = Categories::model()->findAll('`parent_id` IS NULL');
        }
        $this->render('categories', array('model'=>$model));
    }

    public function actionProductsByCategory($id)
    {
        if(!isset($_POST['Product'])) {
            $_POST['Product'] = array();
        }
        $_POST['Product']['category_id'] = $id;
        $this->forward('products');
        Yii::app()->end();
    }

    public function actionProducts($view = 'list')
    {
        $model = new Product('search');
        $model->unsetAttributes();
        if(Yii::app()->request->getParam('Product') !== null) {
            $model->attributes = Yii::app()->request->getParam('Product');
        }
        $dataProvider =$model->search();
        $dataProvider->sort->attributes = array(
            'status'=>array(
                'asc'=>Product::getStatusSort().'ASC',
                'desc'=>Product::getStatusSort().'DESC',
                'label'=>'По наличию',
            ),
            'price'=>array(
                'asc'=>'price ASC',
                'desc'=>'price DESC',
                'label'=>'По цене',
            ),
            'title'=>array(
                'asc'=>'title ASC',
                'desc'=>'title DESC',
                'label'=>'По названию'
            ),
        );
        $dataProvider->pagination->pageSize = 12;
        $dataProvider->sort->defaultOrder = array('title'=>CSort::SORT_ASC);
        $this->render('products', array('dataProvider'=>$dataProvider,'type'=>$view,'model'=>$model));
    }

    public function actionProduct($id)
    {
        $model = Product::model()->findByPk($id);
        if (!isset($model)) {
            throw new CHttpException(404, 'Товар не найден!');
        }
        if(Yii::app()->user->checkAccess('product.update')) {
            $this->menuItem = array('label'=>'Изменение товара', 'url'=>array('/product/update','id'=>$id));
        }
        $this->render('product',array('model'=>$model));
    }

    public function actionDelivery()
    {
        $this->render('delivery');
    }

    public function actionAddToCart($id)
    {
        $model = Product::model()->findByPk($id);
        if (!isset($model)) {
            Yii::app()->user->setFlash('danger','<strong>Ошибка </strong>Товар не найден!');
        } else {
            if($model->isAvailable()) {
                Cart::instance()->add($model);
                Yii::app()->user->setFlash('success', 'Товар добавлен в корзину!');
            } else {
                Yii::app()->user->setFlash('error', 'Вы не можете добавить этот товар в корзину!');
            }
        }
        $this->renderPartial('to_cart',array('cartCount'=>Cart::instance()->count()));
    }

    public function actionClearCart()
    {
        Cart::instance()->clear();
        $this->renderPartial('clear_cart');
    }

    public function actionCart()
    {
        $cart = Cart::instance()->getCart();
        $this->render('cart',array('cart'=>$cart));
    }

    public function actionRemoveFromCart()
    {
        header('Content-Type: application/json; charset=utf-8');
        $id = Yii::app()->request->getParam('id');
        if(!isset($id)) {
            echo CJavaScript::encode(false);
        } else {
            echo CJavaScript::encode(Cart::instance()->remove($id));
        }
        Yii::app()->end();
    }
}

protected/views/shop/_categories.php
<?php
foreach ($categories as $category){
    echo CHtml::openTag('li', array('class'=>isset($class)?$class:''));
    echo CHtml::link($category->name, array('category','id'=>$category->id));
    echo CHtml::closeTag('li');
}

protected/views/shop/_search.php
<div class="panel search-form" hidden="hidden">
    <?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm',array(
        'type'=>'horizontal',
    ));/** @var TbActiveForm $form */ ?>
    <?php
    $materials = CHtml::listData(Materials::model()->findAll(), 'id','name');
    $materials = CMap::mergeArray(array(null=>'Не важно'),$materials);
    ?>
    <fieldset>
        <legend>Расширенный поиск</legend>
        <?= $form->textFieldRow($model,'title',array('class'=>'span5'));?>
        <div class="control-group">
            <?= $form->label($model,'width',array('class'=>'control-label'))?>
            <div class="controls controls-row">
                <div class="input-append input-prepend span5">
                    <span class="add-on">От: </span>
                    <?= $form->textField($model,'width',array('class'=>'span5'))?>
                    <span class="add-on">До: </span>
                    <?= $form->textField($model,'widthTo',array('class'=>'span5'))?>
                    <span class="add-on">мм.</span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <?= $form->label($model,'height',array('class'=>'control-label'))?>
            <div class="controls controls-row">
                <div class="input-append input-prepend span5">
                    <span class="add-on">От: </span>
                    <?= $form->textField($model,'height',array('class'=>'span5'))?>
                    <span class="add-on">До: </span>
                    <?= $form->textField($model,'heightTo',array('class'=>'span5'))?>
                    <span class="add-on">мм.</span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <?= $form->label($model,'length',array('class'=>'control-label'))?>
            <div class="controls controls-row">
                <div class="input-append input-prepend span5">
                    <span class="add-on">От: </span>
                    <?= $form->textField($model,'length',array('class'=>'span5'))?>
                    <span class="add-on">До: </span>
                    <?= $form->textField($model,'lengthTo',array('class'=>'span5'))?>
                    <span class="add-on">мм.</span>
                </div>
            </div>
        </div>
        <div class="control-group">
            <?= $form->label($model,'price',array('class'=>'control-label'))?>
            <div class="controls controls-row">
                <div class="input-append input-prepend span5">
                    <span class="add-on">От: </span>
                    <?= $form->textField($model,'price',array('class'=>'span5'))?>
                    <span class="add-on">До: </span>
                    <?= $form->textField($model,'priceTo',array('class'=>'span5'))?>
                    <span class="add-on">руб.</span>
                </div>
            </div>
        </div>
        <?= $form->dropdownListRow($model,'category_id',CHtml::listData(Categories::getAllFree(true),'id','name'),array('class'=>'span5'));?>
        <?= $form->dropdownListRow($model,'material_id',$materials,array('class'=>'span5'));?>
        <?= $form->dropdownListRow($model,'status',Product::getStatuses(true),array('class'=>'span5'));?>
        <?= $form->textAreaRow($model,'description',array('class'=>'span5'));?>
    </fieldset>
    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton',array(
            'type'=>'primary',
            'icon'=>'search',
            'label'=>'Поиск',
            'buttonType'=>'submit',
            'htmlOptions'=>array(
                'id'=>'searchButton',
            ),
        ));?>
    </div>
    <?php $this->endWidget();?>
</div>

protected/views/shop/_view_grid.php
<?php
$image = Yii::app()->baseUrl.'/images/none.png';
Yii::app()->clientScript->registerCssFile(Yii::app()->assetManager->publish(Yii::getPathOfAlias('webroot.css.grid').'.css'));
if(isset($data->images)) {
    $image = Yii::app()->baseUrl.'/images/Product/'.unserialize($data->images)[0];
}
$description = $data->description;
if(strlen($description) > 200) {
    $description = substr($description,0,100).'...';
}
?>
<li class="col-3 padd-1-1">
    <div class="thumbnail product-in-grid">
        <div>
            <div class="product-image" style="height:100px; margin:0 auto; background-image:url('<?php echo $image;?>');"></div>
            <h3 class="text-center"><?= CHtml::link($data->title.'',array('shop/product','id'=>$data->id)); ?></h3>
            <p class="text-center product-status"><span class="label label-<?= $data->statusAsLabelClass; ?>"><?= $data->userStatus; ?></span></p>
            <div style="padding: 0 10px;">
                <p><?= $description ?></p>
                <p><strong>Высота: </strong><span class="pull-right"><?= $data->width;?>мм.</span></p>
                <p><strong>Ширина: </strong><span class="pull-right"><?= $data->height;?>мм.</span></p>
                <p><strong>Глубина: </strong><span class="pull-right"><?= $data->length;?>мм.</span></p>
                <p><strong>Артикул: </strong><span class="pull-right"><?php printf('%05d',$data->id); ?></span></p>
                <p><strong>Цена: </strong><span class="pull-right"><?= $data->price; ?><i class="icon-rub"></i></span></p>
            </div>
        </div>
        <p class="text-center grid-to-cart"><?php $this->widget('bootstrap.widgets.TbButton', array(
                'type'=>'success',
                'buttonType'=>'ajaxButton',
                'icon'=>'shopping-cart',
                'url'=>array('shop/addToCart','id'=>$data->id),
                'label'=>'В корзину',
                'disabled'=>!$data->isAvailable(),
                'ajaxOptions'=>array('update'=>'#alerts'),
            ));?></p>
    </div>
</li>

protected/views/shop/_view_list.php
<?php
/**
 * @var ShopController $this
 */
?>
<?php
$image = Yii::app()->baseUrl.'/images/none.png';
if(isset($data->images)) {
    $image = Yii::app()->baseUrl.'/images/Product/'.unserialize($data->images)[0];
}
$description = $data->description;
if(strlen($description) > 200) {
    $description = substr($description,0,200).'...';
}
?>
<div class="panel product-in-list">
    <div class="row-fluid">
        <div class="span4">
            <a class="thumbnail" href="<?= $this->createUrl('shop/product', array('id'=>$data->id)); ?>">
                <div class="product-image" style="height:200px;background-image: url('<?= $image; ?>');"></div>
            </a>
        </div>
        <div class="span8 pull-right">
            <div class="span8">
                <h3><?= CHtml::link($data->title,array('shop/product',array('id'=>$data->id))); ?></h3>
                <div class="row-fluid">
                    <div class="span8"><p><?= $description ?></p></div>
                    <div class="span4">
                        <p><strong>Высота: </strong><span class="pull-right"><?= $data->width;?>мм.</span></p>
                        <p><strong>Ширина: </strong><span class="pull-right"><?= $data->height;?>мм.</span></p>
                        <p><strong>Глубина: </strong><span class="pull-right"><?= $data->length;?>мм.</span></p>
                        <p><strong>Артикул: </strong><span class="pull-right"><?php printf('%05d',$data->id); ?></span></p>
                    </div>
                </div>
            </div>
            <div class="span4 text-center pull-right">
                <p class="h3 product-price"><span class="h2"><?= $data->price; ?></span><i class="icon-rub"></i></p>
                <p class="product-status"><span class="label label-<?= $data->statusAsLabelClass; ?>"><?= $data->userStatus; ?></span></p>
                <div><?php $this->widget('bootstrap.widgets.TbButton', array(
                        'type'=>'success',
                        'buttonType'=>'ajaxButton',
                        'size'=>'large',
                        'disabled'=>!$data->isAvailable(),
                        'icon'=>'shopping-cart',
                        'url'=>array('shop/addToCart','id'=>$data->id),
                        'label'=>'В корзину',
                        'ajaxOptions'=>array('update'=>'#alerts'),
                        'htmlOptions'=>$data->isAvailable()?null:array(
                            'rel'=>'tooltip',
                            'title'=>'Эта опция доступна только для зарегестрированных пользователей',
                        ),
                ));?></div>
            </div>
        </div>
    </div>
</div>

protected/views/shop/cart.php
<?php
Yii::app()->clientScript->registerCssFile(Yii::app()->assetManager->publish(Yii::getPathOfAlias('webroot.css.fontello').'.css'));
$this->pageTitle = Yii::app()->name.' - Магазин - Корзина';
$price = 0;
Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/cart.js');
Yii::app()->clientScript->registerScript('cart_defines',
    'window.address = \''.$this->createUrl('/shop/removeFromCart'.'\';'.
    'window.errorMessage = "<div class=\'alert in fade alert-block alert-danger\'><a class=\'close\' data-dismiss=\'alert\'>&times;</a><strong>Ошибка</strong> Повторите запрос позже</div>";'
    ));
$orderPermission = Yii::app()->user->checkAccess('orders.custom');
foreach ($cart as $product) {
    $price += $product->price;
}
if (count($cart) > 0):
?>
    <div id="cart">
        <div class="panel search-panel">
            <div class="cart-total span6">
                    <strong>Всего товаров</strong>: <span class="badge badge-info"><?= count($cart);?></span> <strong>На сумму</strong>: <?= $price; ?><i class="icon-rub"></i>
            </div>
            <div class="cart-operations span6 text-right">
                <?php if (count($cart) > 0) {
                    $this->widget('bootstrap.widgets.TbButton', array(
                        'type' => 'success',
                        'icon' => 'ok',
                        'url' => array('orders/create'),
                        'label' => 'Оформить заказ',
                    ));
                    echo ' ';
                    $this->widget('bootstrap.widgets.TbButton', array(
                        'type' => 'danger',
                        'buttonType' => 'ajaxLink',
                        'icon' => 'trash',
                        'url' => array('shop/clearCart'),
                        'label' => 'Очистить корзину',
                        'ajaxOptions' => array('update' => '#cart'),
                        'htmlOptions' => array('id'=>'clearCart'),
                    ));
                } else {
                }
                ?>
            </div>
        </div>
        <div id="cart-elements">
            <table class="table table-hover table-striped">
                <tr>
                    <th>Название</th>
                    <th>Цена,<i class="icon-rub"></i></th>
                    <th>Действия</th>
                </tr>
                <?php foreach ($cart as $key => $product):?>
                <tr>
                    <td><?= $product->title; ?></td>
                    <td><?= $product->price; ?></td>
                    <td>
                        <a href="#" rel="tooltip" title="Удалить" class="delete-cart-element" data-key="<?= $key; ?>"><i class="icon icon-trash"></i></a>
                        <?= CHtml::link('<i class="icon icon-eye-open"></i>', array('shop/product','id'=>$product->id),array(
                            'rel'=>'tooltip',
                            'title'=>'Просмотр',
                        )); ?>
                        <?php if ($orderPermission) {
                            echo CHtml::link('<i class="icon icon-pencil"></i>',array('/orders/custom','id'=>$product->id),array(
                                'rel'=>'tooltip',
                                'title'=>'"На заказ!"'
                            ));
                        } ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
<?php else: ?>
<div class="text-center panel">
    <?php
    $randProduct = Product::random();
    echo 'Ваша корзина пуста! Как на счёт "'.CHtml::link($randProduct->title,array('/shop/product','id'=>$randProduct->id)).'"?';
    ?>
</div>
<?php endif; ?>

protected/views/shop/clear_cart.php
<script type="text/javascript">
    $('#cart-link-badge').text('0');
</script>
<div class="text-center panel">
    <?php
    $randProduct = Product::random();
    echo 'Ваша корзина пуста! Как на счёт "'.CHtml::link($randProduct->title,array('/shop/product','id'=>$randProduct->id)).'"?';
    ?>
</div>