protected/models/Users.php
<?php

/**
 * This is the model class for table "tbl_users".
 *
 * The followings are the available columns in table 'tbl_users':
 * @property string $id
 * @property string $login
 * @property string $email
 * @property string $name
 * @property integer $passwd
 * @property string $role
 */
class Users extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('login, email, name, passwd', 'required'),
			array('passwd', 'numerical', 'integerOnly'=>true),
			array('login', 'length', 'max'=>50),
			array('email', 'length', 'max'=>100),
			array('name', 'length', 'max'=>250),
			array('role', 'length', 'max'=>8),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, login, email, name, passwd, role', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'login' => 'Login',
			'email' => 'Email',
			'name' => 'Name',
			'passwd' => 'Passwd',
			'role' => 'Role',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('login',$this->login,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('passwd',$this->passwd);
		$criteria->compare('role',$this->role,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Users the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/UserController.php
<?php

class UserController extends Controller {

    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha'=>array(
                'class'=>'CCaptchaAction',
                'backColor'=>0xF5F5F5,
                'height'=>35,
                'width'=>100,
            ),
        );
    }

    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',
                'actions'=>array('captcha', 'activate'),
                'users'=>array('*'),
            ),
            array('allow',
                'actions'=>array('index', 'profile', 'logout'),
                'users'=>array('@'),
            ),
            array('allow',
                'actions'=>array('register','login','forgotPassword', 'resetPassword'),
                'roles'=>array('guest'),
            ),
            array('allow',
                'actions'=>array('admin'),
                'roles'=>array('admin'),
            ),
            array('allow',
                'actions'=>array('update'),
                'roles'=>array('admin'),
                'verbs'=>array('POST'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
                'deniedCallback'=>array($this, 'redirectNotAuthorized'),
            ),
        );
    }

    public function actionRegister()
    {
        $model = new RegisterForm('insert');
        if(Yii::app()->request->getParam('RegisterForm') !== null) {
            $this->performAjaxValidation($model);
            $model->attributes = Yii::app()->request->getParam('RegisterForm');
            if ($model->validate()) {
                if ($model->save(false)) {
                    Yii::app()->user->setFlash('success', '<strong>Поздравляем!</strong> Вы успешно зарегестрировались. Ожидайте активационное письмо на ' . $model->email);
                    $mail = new YiiMailMessage();
                    $mail->view = 'registered';
                    $mail->setBody(array('user'=>$model), 'text/html', 'utf-8');
                    $mail->addTo($model->email);
                    $mail->message->setFrom('noreply@'.Yii::app()->request->serverName, 'Баллер Мебель');
                    $mail->subject = 'Активация учётной записи';
                    Yii::app()->mail->send($mail);
                    $this->redirect(Yii::app()->user->returnUrl);
                    Yii::app()->end();
                }
                Yii::app()->user->setFlash('danger', '<strong>Упс!</strong> Что-то пошло не так... Повторите попытку позже.');
            }
        }
        $this->render('register', array('model'=>$model));
    }

    public function actionLogin()
    {
        $model = new LoginForm();
        $this->performAjaxValidation($model);
        if(Yii::app()->request->getParam('LoginForm') !== null) {
            $model->attributes = Yii::app()->request->getParam('LoginForm');
            if ($model->validate()) {
                if ($model->login()) {
                    Yii::app()->user->setFlash('success', '<strong>Здравствуйте</strong> Рады видеть вас снова, ' . Yii::app()->user->name . '!');
                    $this->redirect(Yii::app()->user->returnUrl);
                    Yii::app()->end();
                }
            }
        }
        $this->render('login', array('model'=>$model));
    }

    public function actionLogout()
    {
        Yii::app()->user->logout(false);
        Yii::app()->user->setFlash('success', '<strong>До свидания</strong> Заходите к нам ещё!');
        $this->redirect(Yii::app()->user->returnUrl);
        Yii::app()->end();
    }

    public function actionActivate($id, $securecode)
    {
        $user = RegisterForm::model()->findByPk($id);
        if (!isset($user) || !$user->verifyCode($securecode)) {
            Yii::app()->user->setFlash('danger', '<strong>Ошибка</strong> Проверьте правильность ссылки!');
        } else {
            $user->role = 'user';
            if($user->save(false)) {
                Yii::app()->user->setFlash('success', '<strong>Поздравляем</strong> Вы успешно активировали аккаунт!');
            } else {
                Yii::app()->user->setFlash('warning', '<strong>Ошибка</strong> Во время активации произошла ошибка. Повторите запрос позже.');
            }
        }
        $this->redirect(array('/'));
        Yii::app()->end();
    }

    public function actionForgotPassword()
    {
        $email = Yii::app()->request->getParam('email');
        if (isset($email) && $email !== '') {
            $user = RegisterForm::model()->findByAttributes(array(
                'email' => $email,
            ));
            if (!isset($user)) {
                Yii::app()->user->setFlash('warning', 'Пользователь с указанным email не найден!');
            } else {
                $mail = new YiiMailMessage();
                $mail->view = 'password';
                $mail->setBody(array('user'=>$user), 'text/html', 'utf-8');
                $mail->addTo($user->email);
                $mail->message->setFrom('noreply@'.Yii::app()->request->serverName, 'Баллер Мебель');
                $mail->subject = 'Восстановление пароля';
                Yii::app()->mail->send($mail);
                Yii::app()->user->setFlash('success', 'Инструкции по восстановлению отправлены на '.$user->email);
                $this->redirect(Yii::app()->user->returnUrl);
                Yii::app()->end();
            }
        }
        $this->render('password');
    }

    public function actionResetPassword($id, $secureCode)
    {
        $user = RegisterForm::model()->findByPk($id);
        if (!isset($user) || !$user->verifyCode($secureCode)) {
            Yii::app()->user->setFlash('danger', '<strong>Ошибка</strong> Проверьте правильность ссылки!');
        } else {
            $password = substr(uniqid(), 0, 8);
            $user->passwd = CPasswordHelper::hashPassword($password);
            if($user->save(false)) {
                $mail = new YiiMailMessage();
                $mail->view = 'password_new';
                $mail->setBody(array(
                    'user' => $user,
                    'password' => $password,
                ), 'text/html', 'utf-8');
                $mail->addTo($user->email);
                $mail->message->setFrom('noreply@'.Yii::app()->request->serverName, 'Баллер Мебель');
                $mail->subject = 'Восстановление пароля';
                Yii::app()->mail->send($mail);
                Yii::app()->user->setFlash('success', '<strong>Поздравляем</strong> Ваш новый пароль отправлен на '.$user->email);
            } else {
                Yii::app()->user->setFlash('warning', '<strong>Ошибка</strong> Во время восстановления пароля произошла ошибка. Повторите запрос позже.');
            }
        }
        $this->redirect(Yii::app()->user->returnUrl);
        Yii::app()->end();
    }

    public function actionAdmin()
    {
        $model = new UserDataModel('search');
        $model->unsetAttributes();
        if(Yii::app()->request->getParam('UserDataModel') !== null) {
            $model->attributes = Yii::app()->request->getParam('UserDataModel');
        }
        $this->render('admin', array('model'=>$model));
    }

    public function actionUpdate($id)
    {
        header('Content-Type: application/json; charset=utf-8');
        $model = UserDataModel::model()->findByPk($id);
        if (!isset($model)) {
            echo CJavaScript::jsonEncode(array('code'=>404,'id'=>$id));
            Yii::app()->end();
        }
        $model->attributes = Yii::app()->request->getParam('UserDataModel');
        $code = $model->save(false)?200:500;
        echo CJavaScript::jsonEncode(array('code'=>$code,'id'=>$id,'attributes'=>$model->attributes,'post'=>Yii::app()->request->getParam('UserDataModel')));
        Yii::app()->end();
    }

}

protected/views/user/_search.php
<br><?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    'action'=>Yii::app()->createUrl($this->route),
    'method'=>'get',
    'htmlOptions'=>array('class'=>'panel'),
)); ?>

<?php echo $form->textFieldRow($model,'login',array('class'=>'span5')); ?>
<?php echo $form->textFieldRow($model,'email',array('class'=>'span5')); ?>
<?php echo $form->textFieldRow($model,'name',array('class'=>'span5')); ?>
<?php echo $form->dropdownListRow($model,'role',UserDataModel::getStatuses(),array('class'=>'span5')); ?>


<div class="form-actions">
    <?php $this->widget('bootstrap.widgets.TbButton', array(
        'buttonType'=>'submit',
        'type'=>'primary',
        'label'=>'Поиск',
    )); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/user/admin.php
<?php
$this->breadcrumbs=array(
    'Административная панель'=>array('/panel'),
    'Управление пользователями',
);

$this->pageTitle = Yii::app()->name.' - Управление пользователями';

Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl.'/js/users.js');
Yii::app()->clientScript->registerScript('statuses', 'var statuses = '.CJavaScript::encode(CHtml::dropDownList('UserDataModel[role]',0,UserDataModel::getStatuses())).';', CClientScript::POS_HEAD);
Yii::app()->clientScript->registerScript('submitChange', '$("#userDataModalSubmit").click(function(){submitChanges("'.$this->createUrl('update').'");return false;});');

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('categories-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<?php $this->beginWidget('bootstrap.widgets.TbModal', array('id'=>'userDataModal'));?>
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4>Пользователь "<span id="userName"></span>"</h4>
    </div>
    <div class="modal-body">
        <div id="userLoading" class="grid-view-loading">
        </div>
        <div class="data"></div>
    </div>
    <div class="modal-footer">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>'Сохранить',
            'url'=>'#',
            'type'=>'primary',
            'htmlOptions'=>array(
                'id'=>'userDataModalSubmit',
            ),
        )); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'label'=>'Закрыть',
            'url'=>'#',
            'htmlOptions'=>array('data-dismiss'=>'modal'),
        )); ?>
    </div>
<?php $this->endWidget(); ?>

<h1>Администрирование пользователей</h1>

<p>
    Вы можете добавить оператор сравнения (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
    или <b>=</b>) в начало каждого поля для определения способа сравнения.
</p>

<?php echo CHtml::link('Расширенный поиск','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
    <?php $this->renderPartial('_search',array(
        'model'=>$model,
    )); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
    'id'=>'categories-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        array(
            'name'=>'login',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по имени пользователя'
            ),
        ),
        array(
            'name'=>'email',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по email'
            ),
        ),
        array(
            'name'=>'name',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по имени'
            ),
        ),
        array(
            'name'=>'role',
            'filterWrapTag'=>'a',
            'filterWrapHtmlOptions'=>array(
                'rel'=>'tooltip',
                'title'=>'Поиск по статусу'
            ),
            'value'=>'UserDataModel::roleToStatus($data->role)',
            'filter'=>UserDataModel::getStatuses(),
        ),
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'header'=>'Действия',
            'viewButtonUrl'=>'"javascript:showUserData(".CJavascript::encode(CMap::mergeArray($data->attributes,array("status"=>UserDataModel::roleToStatus($data->role),"passwd"=>""))).")"',
            'updateButtonUrl'=>'"javascript:showChangePromt(".CJavascript::encode(CMap::mergeArray($data->attributes,array("status"=>UserDataModel::roleToStatus($data->role),"passwd"=>""))).")"',
            'template'=>'{view} {update}',
        ),
    ),
    'template'=>'<div class="row-fluid"><div class="span6 cv">{pager}</div><div class="span6 cv">{summary}</div></div><div>{items}</div><div class="text-center">{pager}</div>',
    'type'=>'hover',
    'summaryText'=>'Страница {page} из {pages}',
)); ?>

protected/views/user/login.php
<div class="span6">
    <?php
    /**
     * @var UserController $this
     * @var LoginForm $model
     */
    $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'verticalForm',
        'type'=>'horizontal',
        'htmlOptions'=>array('class'=>'panel'),
        'enableAjaxValidation'=>true,
        'enableClientValidation'=>true,
    ));
    $this->pageTitle = Yii::app()->name.' - Вход';
    $this->breadcrumbs = array('Вход');
    Yii::app()->clientScript->registerCss('noRequired', 'label.required > span.required { '.
                                                            'display:none;'.
                                                        '}');
    ?>

    <div class="row-fluid"><?php echo $form->textFieldRow($model, 'login', array('class'=>'span12')); ?></div>
    <div class="row-fluid"><?php echo $form->passwordFieldRow($model, 'password', array('class'=>'span12')); ?></div>
    <div class="row-fluid"><?php echo $form->checkboxRow($model, 'rememberme', array('class'=>'')); ?></div>
    <div class="row-fluid">
        <div class="span12 text-center">
            <div class="span4 offset4">
                <?php $this->widget('bootstrap.widgets.TbButton', array(
                    'buttonType'=>'submit',
                    'label'=>'Вход',
                    'htmlOptions'=>array('class'=>'span12'),
                )); ?>
                <?php $this->widget('bootstrap.widgets.TbButton', array(
                    'buttonType'=>'link',
                    'label'=>'Забыли пароль?',
                    'url' => array('user/forgotPassword'),
                    'htmlOptions'=>array('class'=>'span12 btn-link'),
                )); ?>
            </div>
        </div>
    </div>

    <?php $this->endWidget(); ?>
</div>
<div class="span6">
    <div class="panel">
        <p>Если у вас ещё нет учётной записи, вы можете <?php echo CHtml::link('зарегистрироваться', array('/user/register'));?>.</p>
    </div>
</div>

protected/views/user/password.php
<?php
$this->pageTitle = Yii::app()->name . ' - Восстановление пароля';
$this->breadcrumbs = array(
    'Восстановление пароля'
);
?>

<div class="span6 offset3">
    <form class="form-horizontal panel row-fluid" method="POST">
        <div class="span6 offset3">
            <div class="row-fluid">
                <div class="span4">
                    <label for="email">Email</label>
                </div>
                <div class="span8">
                    <input type="email" name="email" id="email">
                </div>
            </div>
            <p></p>
            <div class="row-fluid">
                <div class="span8 offset4">
                    <button class="btn btn-default">Восстановить</button>
                </div>
            </div>
        </div>
    </form>
</div>

protected/views/user/register.php
<div class="span6">
    <div class="alert alert-info">
        Поля помеченные <span class="required">*</span> обязательны для заполнения.
    </div>
    <?php
    /**
     * @var $this UserController
     * @var $model RegisterForm
     */

    /// @var $form TbActiveForm
    $this->breadcrumbs = array('Регистрация');
    $this->pageTitle = Yii::app()->name.' - Регистрация';
    $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'verticalForm',
        'type'=>'horizontal',
        'htmlOptions'=>array('class'=>'panel'),
        'enableAjaxValidation'=>true,
        'enableClientValidation'=>true,
        'focus'=>array($model, 'login'),
    ));
    $form->errorSummary($model);
    ?>
    <div class="row-fluid"><?php echo $form->textFieldRow($model, 'login', array('class'=>'span12', 'placeholder'=>'Логин')); ?></div>
    <div class="row-fluid"><?php echo $form->textFieldRow($model, 'email', array('class'=>'span12')); ?></div>
    <div class="row-fluid"><?php echo $form->passwordFieldRow($model, 'passwd', array('class'=>'span12')); ?></div>
    <div class="row-fluid"><?php echo $form->passwordFieldRow($model, 'passwd_repeat', array('class'=>'span12')); ?></div>
    <div class="row-fluid"><?php echo $form->textFieldRow($model, 'name', array('class'=>'span12')); ?></div>
    <div class="row-fluid"><?php echo $form->textFieldRow($model, 'captcha', array(
            'class'=>'span12',
        )); ?></div>
    <div class="row-fluid">
        <div class="control-group">
            <div class="control-label">Код:</div>
            <div class="controls">
                <a class="thumbnail" style="height: 20px; overflow: hidden;" rel="tooltip" data-title="Нажмите для генерации новой картинки">
                    <?php $this->widget('CCaptcha', array(
                        'clickableImage'=>true,
                        'showRefreshButton'=>false,
                        'imageOptions'=>array(
                            'style'=>'margin-top: -7.5px;'
                        ),
                    ));?>
                </a>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <p class="help-block">
            Продолжая процедуру регистрации, вы соглашаетесь с <?= CHtml::link('условиями использования',array('/page/terms'));?>.
        </p><br/>
        <div class="span12 text-center">
            <?php
            $this->widget('bootstrap.widgets.TbButton', array(
                'buttonType'=>'submit',
                'type'=>'primary',
                'label'=>'Зарегистрироваться',
            ));
            ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div>
<div class="span6 panel">
    <strong>Какие преимущества даёт регистрация?</strong>
    <ul>
        <li>Оформление мебели <em>"под заказ"</em></li>
        <li>Возможность отслеживать статус оформления заказа</li>
        <li>...</li>
    </ul>
</div>